### ISSUE TITLE
Image messages does not shown up on iPhone

### ISSUE THREAD

**Issue by tdermaris** [cometchat-pro/ios-swift-chat-ui-kit#11]
The problem
If you try to send a relatively large(2-3MB) image on iPhone, you only see a grey frame. You have to scroll the message list up and down in order to see the image

Expected behavior?
As soon as the image has been downloaded, you have to see the image in the message list

Reproduction
Just send a large image on an iPhone

Environment
UIKit 2.1.12

**Comment by pushpsenairekar2911** [comment]
Hello @tdermaris, 

To resolve this issue, you can enable the thumbnail extension from CometChatPro Dashboard, After enabling it will be applicable for the newer images sent after an extension is enabled.

Regards, 
Pushpsen R. Airekar
