### ISSUE TITLE
Not working with CometChatPro 2.3.5

### ISSUE THREAD

**Issue by AdamBCo** [cometchat-pro/ios-swift-chat-ui-kit#13]
The files in the repository don't work with CometChatPro 2.3.5.

When integrating these files into an existing project, I face a wide variety of errors including:
- Cannot override with a stored property 'heightConstraint'
- Cannot override 'strong' property with 'weak' property
- Cannot override with a stored property 'centerXConstraint'
- Ambiguous use of 'seconds'

Can someone please update the code to work with the new version of CometChatPro?

**Comment by pushpsenairekar2911** [comment]
Hello @AdamBCo, 

Are you also using the Kingfisher library inside your project? If yes, then please use CometChatKingfisher which is already included in the library. 
Let me know if you're still facing any issues? 

Regards, 
Pushpsen R. Airekar
