### ISSUE TITLE
Swift UI compatibility

### ISSUE THREAD

**Issue by karvelasx** [cometchat-pro/ios-swift-chat-ui-kit#18]
It seems that swiftUI is not supported. From the class below you can understand that every swiftUI component is deprecated according to the Deprecated.swift file in the Library. Is there any workaround for that?  

@available(*, deprecated, message: "Use `CFCrossPlatformImage` instead.")
 typealias Image = CFCrossPlatformImage
@available(*, deprecated, message: "Use `CFCrossPlatformView` instead.")
 typealias View = CFCrossPlatformView
@available(*, deprecated, message: "Use `CFCrossPlatformColor` instead.")
 typealias Color = CFCrossPlatformColor
@available(*, deprecated, message: "Use `CFCrossPlatformImageView` instead.")
 typealias ImageView = CFCrossPlatformImageView
@available(*, deprecated, message: "Use `CFCrossPlatformButton` instead.")
 typealias Button = CFCrossPlatformButton
#else
@available(*, deprecated, message: "Use `CFCrossPlatformImage` instead.")
 typealias Image = CFCrossPlatformImage
@available(*, deprecated, message: "Use `CFCrossPlatformColor` instead.")
 typealias Color = CFCrossPlatformColor
    #if !os(watchOS)
    @available(*, deprecated, message: "Use `CFCrossPlatformImageView` instead.")
     typealias ImageView = CFCrossPlatformImageView
    @available(*, deprecated, message: "Use `CFCrossPlatformView` instead.")
     typealias View = CFCrossPlatformView
    @available(*, deprecated, message: "Use `CFCrossPlatformButton` instead.")
     typealias Button = CFCrossPlatformButton
    #endif
#endif

**Comment by pushpsenairekar2911** [comment]
Hi @karvelasx, 

Our current UI Kit is not supported for SwiftUI. We'll release the new UI Kit separately in the upcoming days. Please upvote this link so that you'll get notified when we release this support. 

https://feedback.cometchat.com/ui-kits/p/swift-ui-compatibility

Thanks. 

Regards, 
Pushpsen R. Airekar
