### ISSUE TITLE
Code contains merge conflicts <<<<<<< HEAD

### ISSUE THREAD

**Issue by LaurentiuUngur** [cometchat-pro/ios-swift-chat-ui-kit#20]
### Describe the problem

Please check that in some classes there is code related to merge conflicts. Please search for <<<<<<< HEAD

**CometChatMeetingView** for example
<img width="662" alt="Screenshot 2022-09-17 at 07 44 24" src="https://user-images.githubusercontent.com/13499785/190840847-61a94ec8-d2f4-4eae-b832-4c02e0abb27a.png">

### What was the expected behavior?

It must not contain those <<<<<<< HEAD, otherwise it won't compile

### Environment

- **Version used:**  v3.0.909-1

**Comment by LaurentiuUngur** [comment]
1. iOS, native iOS development
2.   - CometChatCalls (2.2.0):
    - CometChatWebRTC (= 1.100.0)
  - CometChatPro (3.0.909)
  - CometChatWebRTC (1.100.0)
3. UI Kit

**Comment by pushpsenairekar2911** [comment]
Hi @LaurentiuUngur  

We have pushed the patch for this issue, please clone the new library and add it to your project. 
Let us know if you face any issues. 

Pushpsen Airekar
Senior Product Engineer
CometChat
