### ISSUE TITLE
App is crashing When I try to create a new group

### ISSUE THREAD

**Issue by shadowwalkersteam** [cometchat-pro/ios-swift-chat-ui-kit#8]
I have recently purchased the plan of COMETCHAT PRO. I'm facing an issue when I create Group it crashes immediately. However if i launch the app again the group was created. 
Using Xcode 11.5
iOS 13.5.1

Below are the error details:
Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file /Users/nishanttiwari/Documents/Nishant/dev/cometchat-pro-ios-sdk/CometChatSDK/CometChatPro/Manager/XMPP/XMPPController.swift, line 187

This is works fine in your sample application. I'm using the same code, Nothing has changed but it works fine in your sample app but not in my own app.

**Comment by pushpsenairekar2911** [comment]
Hello @shadowwalkersteam, 

Please let us know If you are still facing this issue. I think our team is connected with you on the forum. Still, you're facing this issue then we are happy to help.

**Comment by shadowwalkersteam** [comment]
@pushpsenairekar2911 Yes I'll update you guys once I get back to work

**Comment by pushpsenairekar2911** [comment]
Hello @shadowwalkersteam, 

We have fixed this issue in SDK version 2.0.13. Please update your profile and update your pods. After updating to the latest version of SDK this issue will automatically get resolved.
